import React from 'react';
import { X, ArrowUpRight, ShieldCheck, TrendingUp, Users, Calendar, Wallet } from 'lucide-react';
import { EarningStats, Transaction } from '../types';

interface DetailsModalProps {
  cardType: 'today' | 'sevenDays' | 'thirtyDays' | 'allTime' | 'passive' | null;
  earnings: EarningStats;
  transactions: Transaction[];
  onClose: () => void;
  onRequestPayout: () => void;
}

export const DetailsModal: React.FC<DetailsModalProps> = ({
  cardType,
  earnings,
  transactions,
  onClose,
  onRequestPayout,
}) => {
  if (!cardType) return null;

  const cardConfig = {
    today: {
      title: "Today's Earning Details",
      amount: earnings.today,
      gradient: 'from-[#D81B60] to-[#9D157F]',
      badge: 'Live Daily Snapshot',
      icon: TrendingUp,
      subtitle: 'Commissions credited from direct sales and downline conversions today.',
    },
    sevenDays: {
      title: '7 Days Earning Details',
      amount: earnings.sevenDays,
      gradient: 'from-[#6D28D9] to-[#4C1D95]',
      badge: 'Weekly Performance',
      icon: Calendar,
      subtitle: 'Total commissions accumulated over the past 7 rolling days.',
    },
    thirtyDays: {
      title: '30 Days Earning Details',
      amount: earnings.thirtyDays,
      gradient: 'from-[#1E40AF] to-[#172554]',
      badge: 'Monthly Cumulative',
      icon: Calendar,
      subtitle: 'Monthly performance including direct course sales and team royalties.',
    },
    allTime: {
      title: 'All Time Earning Summary',
      amount: earnings.allTime,
      gradient: 'from-[#7C3AED] to-[#581C87]',
      badge: 'Lifetime Achievements',
      icon: ShieldCheck,
      subtitle: 'Total lifetime income earned since registration with Skill Grow IND.',
    },
    passive: {
      title: 'Passive Income Breakdown',
      amount: earnings.passiveIncome,
      gradient: 'from-[#EA580C] to-[#D97706]',
      badge: 'Tier 1 & Tier 2 Royalties',
      icon: Users,
      subtitle: 'Automated recurring royalties generated by your active team downline.',
    },
  }[cardType];

  const filteredTxns = transactions.filter((t) => {
    if (cardType === 'passive') {
      return t.type === 'PASSIVE_TIER_1' || t.type === 'PASSIVE_TIER_2';
    }
    if (cardType === 'today') {
      return t.date.toLowerCase().includes('today') || true;
    }
    return true;
  });

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-black/60 backdrop-blur-xs animate-fade-in">
      <div
        id="details-modal-container"
        className="bg-white w-full max-w-lg rounded-t-3xl sm:rounded-3xl shadow-2xl overflow-hidden max-h-[90vh] flex flex-col animate-slide-up"
      >
        {/* Header with Card Gradient */}
        <div className={`bg-gradient-to-r ${cardConfig.gradient} p-5 sm:p-6 text-white relative`}>
          <button
            id="close-details-modal-btn"
            onClick={onClose}
            type="button"
            aria-label="Close"
            className="absolute top-4 right-4 p-1.5 rounded-full bg-white/20 hover:bg-white/30 text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>

          <div className="inline-flex items-center space-x-1.5 bg-white/20 text-white text-[11px] font-semibold px-2.5 py-0.5 rounded-full mb-2">
            <cardConfig.icon className="w-3.5 h-3.5" />
            <span>{cardConfig.badge}</span>
          </div>

          <h3 className="text-xl font-bold tracking-tight">{cardConfig.title}</h3>
          <p className="text-xs text-white/80 mt-1 max-w-sm">{cardConfig.subtitle}</p>

          {/* Big Amount */}
          <div className="mt-4 pt-3 border-t border-white/20 flex items-baseline justify-between">
            <span className="text-3xl sm:text-4xl font-extrabold tracking-tight">
              ₹ {cardConfig.amount.toLocaleString('en-IN')}
            </span>
            <span className="text-xs font-medium text-emerald-300 bg-emerald-950/40 px-2.5 py-1 rounded-md border border-emerald-400/30">
              Verified Real-time
            </span>
          </div>
        </div>

        {/* Modal Body */}
        <div className="p-5 overflow-y-auto flex-1 space-y-4 divide-y divide-gray-100">
          {/* Quick Metrics Bar */}
          <div className="grid grid-cols-2 gap-3 pt-1">
            <div className="bg-slate-50 p-3 rounded-xl border border-slate-100">
              <span className="text-[11px] text-gray-500 font-medium">Direct Sales Commission</span>
              <p className="text-base font-bold text-gray-900 mt-0.5">
                ₹ {Math.max(0, cardConfig.amount - earnings.passiveIncome).toLocaleString('en-IN')}
              </p>
            </div>
            <div className="bg-slate-50 p-3 rounded-xl border border-slate-100">
              <span className="text-[11px] text-gray-500 font-medium">Team Royalty (Passive)</span>
              <p className="text-base font-bold text-orange-600 mt-0.5">
                ₹ {Math.min(cardConfig.amount, earnings.passiveIncome).toLocaleString('en-IN')}
              </p>
            </div>
          </div>

          {/* Recent Commission Statement */}
          <div className="pt-4">
            <div className="flex items-center justify-between mb-3">
              <h4 className="text-xs font-bold uppercase tracking-wider text-gray-500">
                Recent Commission Log
              </h4>
              <span className="text-[11px] text-pink-600 font-medium">Auto Payout Mode</span>
            </div>

            {filteredTxns.length === 0 || cardConfig.amount === 0 ? (
              <div className="text-center py-6 bg-gray-50 rounded-xl border border-dashed border-gray-200">
                <p className="text-sm font-semibold text-gray-700">No transactions recorded yet</p>
                <p className="text-xs text-gray-400 mt-1 max-w-xs mx-auto">
                  Share your referral link to start making sales and receiving instant commissions!
                </p>
              </div>
            ) : (
              <div className="space-y-2.5">
                {filteredTxns.map((txn) => (
                  <div
                    key={txn.id}
                    className="flex items-center justify-between p-3 rounded-xl bg-gray-50 hover:bg-gray-100 transition-colors border border-gray-100"
                  >
                    <div className="flex items-center space-x-3">
                      <div
                        className={`w-9 h-9 rounded-lg flex items-center justify-center ${
                          txn.type.includes('PASSIVE')
                            ? 'bg-orange-100 text-orange-600'
                            : 'bg-pink-100 text-pink-600'
                        }`}
                      >
                        <ArrowUpRight className="w-5 h-5" />
                      </div>
                      <div>
                        <p className="text-xs font-bold text-gray-900">{txn.leadName}</p>
                        <p className="text-[11px] text-gray-500">
                          {txn.packageName} • {txn.date}
                        </p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-sm font-bold text-emerald-600">
                        +₹{txn.amount.toLocaleString('en-IN')}
                      </p>
                      <span className="text-[10px] text-gray-400 uppercase tracking-wider font-semibold">
                        {txn.status}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Footer actions */}
        <div className="p-4 border-t border-gray-100 bg-gray-50 flex items-center space-x-3">
          <button
            id="modal-request-payout-btn"
            onClick={() => {
              onClose();
              onRequestPayout();
            }}
            type="button"
            className="flex-1 bg-gradient-to-r from-pink-600 to-purple-600 hover:from-pink-700 hover:to-purple-700 text-white font-semibold py-2.5 px-4 rounded-xl text-sm shadow-md transition-all flex items-center justify-center space-x-2"
          >
            <Wallet className="w-4 h-4" />
            <span>Withdraw / Request Payout</span>
          </button>
          <button
            id="modal-close-action-btn"
            onClick={onClose}
            type="button"
            className="px-4 py-2.5 rounded-xl border border-gray-200 text-gray-700 font-medium text-sm hover:bg-gray-100 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
